### ISSUE TITLE
Filtro por rango de fechas para órdenes

### ISSUE THREAD

**Issue by Frozen-Burrito** [Frozen-Burrito/hydrate-servicio-web#10]
Por el momento, los filtros para órdenes usando un rango de fechas están desactivados. Esto es porque las expresiones usadas por el método Where() de un IQueryable no soportan expresiones complejas, varios statements ni métodos compuestos, como los usados para transformar strings en DateTimes o para comparar dos strings.

Hace falta una forma de filtrar por rango de fecha sin necesidad de usar Where con expresiones compuestas, ya sea con evaluación del cliente o por otros métodos.

**Comment by refmv** [comment]
Solucionado cambiando el tipo de dato de `string` a `DateTime` para hacer las comparaciones de fechas con expresiones aceptadas por LINQ.
