### ISSUE TITLE
Comentarios no se muestran en página de comentarios publicados

### ISSUE THREAD

**Issue by Frozen-Burrito** [Frozen-Burrito/hydrate-servicio-web#7]
Entorno: Produccion

En la página de todos los comentarios publicados, no se muestran los comentarios. Probado con la cuenta prueba5@gmail.com, publicando un comentario antes. El comentario sí aparece en la lista de comentarios del usuario.

**Comment by refmv** [comment]
Hay dos factores que producen esta situación:

1. El comentario creado contiene palabras ofensivas o no tiene palabras claves. En este caso, es el funcionamiento esperado y el filtro de contenido evita la publicación automática del comentario (lo deja como "pendiente").
2. Había un bug en el uso de la función `fetchPaginado()` por las apis de comentarios, en los que las apis pasaban el token de autenticación como argumento en el orden incorrecto. De esta forma, el token enviado con la petición siempre era `null`, o tenía un valor incorrecto. Esto fue solucionado con la PR #22.
